version: '3.7'

services:
  my-backend:
    image: asia.gcr.io/mybackend04/mybackend04:1.8
    build:
      context: .
      dockerfile: Dockerfile.prod
    # volumes:
    #   - ./src:/myfolder/src
    # ports:
    #   - 3000:3000
    # env_file:
    #   - ./.env.prod

  # my-database:
  #   image: mysql:latest
  #   environment:
  #     MYSQL_DATABASE: 'myprod04'
  #     MYSQL_ROOT_PASSWORD: 'root'
  #   ports:
  #     - 3306:3306
